export const SET_HOTELS = "SET_HOTELS";
export const SET_SELECTED_HOTELS = "SET_SELECTED_HOTELS";
export const ADD_HOTEL_IN_SELECTED = "ADD_HOTEL_IN_SELECTED";
export const DELETE_HOTEL_FROM_SELECTED = "DELETE_HOTEL_FROM_SELECTED";

export const SET_QUERY_DEFAULT_PARAMETRES = "SET_QUERY_DEFAULT_PARAMETRES";
export const SET_QUERY = "SET_QUERY";

export const SET_AUTH = "SET_AUTH";

export const GET_HOTELS = "GET_HOTELS";